name: On Pull Request

on:
  pull_request:

jobs:

  on-pull-request:
    name: Get rocks modified and build-scan-test them
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/get-rocks-modified-and-build-scan-test-publish.yaml@main
    permissions:
      pull-requests: read
    secrets: inherit
    with:
      microk8s-channel: 1.31-strict/stable
      juju-channel: 3.6/stable
      python-version: "3.8"
